apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api-deploy
spec:
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api
        image: ndk9999/catalog-rest-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MongoDbSettings__Host
            value: mongodb-service
          - name: MongoDbSettings__Port
            value: "27017"
          - name: MongoDbSettings__User
            value: mongoadmin
          - name: MongoDbSettings__Password
            valueFrom:
              secretKeyRef:
                name: catalog-secrets
                key: mongodb-password
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api-service
spec:
  type: LoadBalancer
  selector:
    app: catalog-api
  ports:
  - port: 8088
    targetPort: 80
