@host=https://localhost:7149

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzM2FlZDc1NC1hNGNhLTRiZjQtYTdlZC1hNjA2N2IzODBjNjEiLCJnaXZlbl9uYW1lIjoiUGh1YyIsImZhbWlseV9uYW1lIjoiTmd1eWVuIiwianRpIjoiOGQwOWU4ODEtN2U0Ny00ZmUxLTk2MjYtYzFjNTNjODJhMDdjIiwiZXhwIjoxNjYxMzIyMDkyLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.UVVVwMwJ3Zh2iRNbNjHkhm0-XavUmICWRPtzkhxSWRg